language: php

php:
    - 7.0
    - 7.1

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    fast_finish: true
    include:
        - php: 7.0
          env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_VERSION=2.8.*
        - php: 7.1
          env: SYMFONY_VERSION=3.2.* SYMFONY_DEPRECATIONS_HELPER=strict

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak

before_script:
    - composer self-update
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update $COMPOSER_FLAGS --prefer-dist --no-interaction
