language: php

cache:
    directories:
        - $HOME/.composer/cache

jobs:
    fast_finish: true
    include:
        - php: 7.2
          env: SYMFONY_VERSION=3.4.* COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.3
          env: SYMFONY_VERSION=4.4.*
        - php: 7.4
          env: SYMFONY_VERSION=5.1.* COMPOSER_FLAGS="--prefer-stable"
        - php: nightly
          env: COMPOSER_FLAGS="--ignore-platform-reqs"

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak
        - COMPOSER_FLAGS="--prefer-dist"

before_install:
    - composer self-update
    - |
      if [ "$SYMFONY_VERSION" != "" ]; then
           sed -ri 's/"symfony\/(.+)": "(.+)"/"symfony\/\1": "'$SYMFONY_VERSION'"/' composer.json;
      fi;

install: composer update $COMPOSER_FLAGS --no-interaction
