name: build

on:
    push:
        branches:
            - master
    pull_request: ~

jobs:
    phpstan:
        runs-on: ubuntu-26.04
        name: PHPStan
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: PHPStan
              uses: docker://oskarstark/phpstan-ga
              env:
                  REQUIRE_DEV: true
              with:
                  args: analyse
    cs-fixer:
        runs-on: ubuntu-26.04
        name: PHP-CS-Fixer
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Fix CS
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                args: --diff --dry-run
    tests:
        runs-on: ubuntu-26.04
        strategy:
            fail-fast: false
            matrix:
                include:
                    - description: 'Symfony 6.4'
                      php: '8.2'
                      symfony: 6.4.*
                      dependencies: lowest
                      max_deprecations: 0
                    - description: 'Symfony 7.4'
                      php: '8.3'
                      symfony: 7.4.*
                      max_deprecations: 0
                    - description: 'Symfony 8.0'
                      php: '8.4'
                      symfony: 8.0.*
                      max_deprecations: 0
                    - description: 'Symfony 8.1'
                      php: '8.5'
                      symfony: 8.1.*
                      max_deprecations: 0
                    - description: 'Symfony 8.2'
                      php: '8.6'
                      symfony: 8.2.*@dev
                      max_deprecations: 0
        name: PHP ${{ matrix.php }} tests (${{ matrix.description }})
        steps:
            - name: Checkout
              uses: actions/checkout@v7
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: flex
            - name: Allow dev dependencies
              run: composer config minimum-stability dev && composer config prefer-stable true
              if: contains(matrix.symfony, '@dev')
            - name: Install dependencies
              uses: ramsey/composer-install@v4
              with:
                  dependency-versions: ${{ matrix.dependencies }}
              env:
                  SYMFONY_REQUIRE: ${{ matrix.symfony }}
            - name: Run tests
              run: vendor/bin/phpunit --colors=always --coverage-clover=clover.xml
              env:
                  SYMFONY_DEPRECATIONS_HELPER: max[self]=${{matrix.max_deprecations}}

